spring:
  application:
    name: starlight
  datasource:
    url: ${STARLIGHT_DATASOURCE_URL:jdbc:h2:file:./data/starlight;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE}
    username: ${STARLIGHT_DATASOURCE_USERNAME:sa}
    password: ${STARLIGHT_DATASOURCE_PASSWORD:}
#    driver-class-name: ${STARLIGHT_DATASOURCE_DRIVER:org.h2.Driver}
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true

starlight:
  theme-dir: ${STARLIGHT_THEME_DIR:themes}
  note-trash:
    retention-days: ${STARLIGHT_NOTE_TRASH_RETENTION_DAYS:30}
    cleanup-cron: ${STARLIGHT_NOTE_TRASH_CLEANUP_CRON:0 20 3 * * *}

sa-token: 
  token-name: starlight-token
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

server:
  port: 8080
